options(repos = c(CRAN = "https://cran.rstudio.com", RSPM = "https://packagemanager.posit.co/cran/2021-06-29"))
getOption("repos")
install.packages('renv')
renv::init(bare = TRUE)
renv::install('butcher@0.1.5', repos = "https://packagemanager.posit.co/cran/2021-06-29", type = "source")
renv::snapshot(type = 'all', confirm = FALSE)
file.copy("renv.lock", "renv.lock.02", overwrite = TRUE)
renv::remove(c('butcher', 'lobstr'))
renv::purge('butcher', prompt = FALSE)
renv::purge('lobstr', prompt = FALSE)
options(repos = c(CRAN = "https://cran.rstudio.com"))
getOption("repos")
renv::restore(prompt = FALSE)
options(repos = c(CRAN = "https://cran.rstudio.com", RSPM = "https://packagemanager.posit.co/cran/2021-06-29", RSPM2 = "https://packagemanager.posit.co/cran/2023-02-22"))
getOption("repos")
renv::install('digest', repos = "https://packagemanager.posit.co/cran/2023-02-22")
renv::snapshot(type = 'all', confirm = FALSE)
file.copy("renv.lock", "renv.lock.02.a", overwrite = TRUE)
renv::remove(c('digest'))
renv::purge('digest', prompt = FALSE)
renv::restore(prompt = FALSE)
library(butcher)
library(lobstr)
library(digest)
